import Head from 'next/head'
import Layout from '../components/layout'
import Button from '../components/button'
import ProjectCluster from '../components/projectCluster'
import ArticleCluster from '../components/articleCluster'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div>
          <article>
            <h1>Sitios web simples, significantes y centrados en las personas</h1>
            <p>Me desempeño en las áreas del diseño de interfáces y el desarrollo front-end de productos o servicios digitales</p>
          </article>
          <article>
            <Button>Ver proyectos</Button>
            <Button>Sobre mí</Button>
          </article>
        </div>
      </section>
      <ProjectCluster
        featured={true}
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
      <section>
        <h2>Últimos artículos</h2>
        <ArticleCluster />
        <ArticleCluster />
        <ArticleCluster />
      </section>
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
    </Layout>
  )
}
