import Head from 'next/head'
import Layout from '../components/layout'
import ButtonLink from '../components/ButtonLink'
import Link from 'next/link'
import ProjectCluster from '../components/projectCluster'
import ArticleCluster from '../components/articleCluster'
import styles from '../styles/pages/home.module.scss'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.hero}>
        <div className={styles.heroWrapper}>
          <article className={styles.heroContainer}>
            <h1 className={styles.heroTitle}>Sitios web simples, significantes y centrados en las personas</h1>
            <p className={styles.heroContent}>Me desempeño en las áreas del diseño de interfáces y el desarrollo front-end de productos o servicios digitales</p>
          </article>
          <div className={styles.heroButtons}>
            <Link href={'/proyectos'} passHref>
              <ButtonLink secondary>Ver proyectos</ButtonLink>
            </Link>
            <Link href={'/sobre-mi'} passHref>
              <ButtonLink>Sobre mí</ButtonLink>
            </Link>
          </div>
        </div>
      </section>
      <Link href='/proyectos'>
        <a>
          <ProjectCluster
            featured={true}
            title={'Redlines'}
            subtitle={'Connecting the dots'}
            imageSrc={'/projects/redlines/portada.png'}
            workType={['Diseño UI', 'Desarrollo Front-End']}
          />
        </a>
      </Link>
      <section className={styles.articlesContainer}>
        <h2 className={styles.articlesTitle}>Últimos artículos</h2>
        <section className={styles.articlesLayout}>
          <ArticleCluster
            imageSrc={'/articles/codigo.png'}
            title={"Contruir una API con GraphQL y MongoDB usando Express.js"}
            excerpt={"Aprende a contruir  una simple API con GraphQL que se comunique con MongoDB. Utiliza un solo endpoint para llenar de contenido tu sitio web"}
            publishDate={"15 de Abril 2021"}
            duration={"7 minutos de lectura"}
          />
          <ArticleCluster
            imageSrc={'/articles/codigo.png'}
            title={"Contruir una API con GraphQL y MongoDB usando Express.js"}
            excerpt={"Aprende a contruir  una simple API con GraphQL que se comunique con MongoDB. Utiliza un solo endpoint para llenar de contenido tu sitio web"}
            publishDate={"15 de Abril 2021"}
            duration={"7 minutos de lectura"}
          />
          <ArticleCluster
            imageSrc={'/articles/codigo.png'}
            title={"Contruir una API con GraphQL y MongoDB usando Express.js"}
            excerpt={"Aprende a contruir  una simple API con GraphQL que se comunique con MongoDB. Utiliza un solo endpoint para llenar de contenido tu sitio web"}
            publishDate={"15 de Abril 2021"}
            duration={"7 minutos de lectura"}
          />
        </section>
      </section>
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
      <ProjectCluster
        title={'Redlines'}
        subtitle={'Connecting the dots'}
        imageSrc={'/projects/redlines/portada.png'}
        workType={['Diseño UI', 'Desarrollo Front-End']}
      />
    </Layout>
  )
}
